---
- name: install zfs-release 
  dnf:
   #name: http://download.zfsonlinux.org/fedora/zfs-release$(rpm -E %dist).noarch.rpm
    name: http://download.zfsonlinux.org/fedora/zfs-release.fc25.noarch.rpm
    state: present
- name: install kernel devel
  dnf:
    name: "kernel-devel-{{ ansible_kernel }}"
    state: present
- name: install zfs
  dnf:
    name: "zfs"
    state: present
- name: install libzfs2-devel
  dnf:
    name: "libzfs2-devel"
    state: present
- name: install git
  dnf:
    name: "git"
    state: present
# Put SELinux in permissive mode, logging actions that would be blocked.
# This was the easiest way I knew to allow zfs-exporter launched by systemd to 
# have read access to the devices/etc.
- selinux:
    policy: targeted
    state: permissive

