---
- hosts: all
  become_user: root
  become: true
  tasks:
  - name: install core python libraries
    raw: dnf install -y python2 python2-dnf libselinux-python
    when: ansible_os_family == "RedHat"
  - name: install core python libraries
    raw: ansible-galaxy install gantsign.golang
